version: "2"

services:
  awsl-pic-pipeline:
    build:
      context: ../
      dockerfile: ./docker/dockerfile
    image: registry.cn-beijing.aliyuncs.com/dreamhunter/awsl:pic-pipeline
    container_name: awsl-pic-pipeline
    environment:
      ENV_FILE: .env
    volumes:
      - ../.env.local:.env
